# action.yml
name: 'action-test'
description: 'this is just a test for github actions'
branding:
  icon: 'log-in'
  color: 'green'
inputs:
  test_env_variable:
    description: 'this is a test input'
    required: true
runs:
  using: 'docker'
  image: 'docker://peachlover/action-test:latest'
  env:
   test_env_variable: ${{ inputs.test_env_variable }}
