# action.yml
name: 'action-test'
description: 'this is just a test for github actions'
branding:
  icon: 'log-in'
  color: 'green'
inputs:
  test:
    description: 'this is a test input'
    required: true
runs:
  using: 'docker'
  image: 'image: docker://861104244336.dkr.ecr.eu-west-1.amazonaws.com/platform_governance/action-test:latest'
  args:
    - ${{ inputs.test }}
